DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS console_logs;

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  ingredients JSONB[],
  directions TEXT[]

  
);

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id),
  date_of_event TEXT NOT NULL,
  notes TEXT NOT NULL,
  rating INTEGER
);